:ekaophx:
  :security_token: 7hEbkfnBDVwEDGKrMW09LfY3
  :friendly_name: ekaophx
  :sandbox_name: ekaophx
  :description: "ekaophx sandbox for Phoenix items"
  :salesforce_url: https://test.salesforce.com/
  :username: ekao@twitter.com.ekaophx
  :password: 
  :client_id: 3MVG9yZ.WNe6byQCWU3mIxk8jzvpxVn760v6gtzWFP5oM0JTM6N_YsJ0wdc.t6Z4LYQ5RtL5VpRo3EXe5sh4y
  :client_secret: "3409656898096009385"